# infra/oci/docker-compose.yml
services:
  traefik:
    image: traefik:v2.10
    command:
      - '--providers.docker=true'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.myresolver.acme.email=admin@joshuatech.dev'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - './traefik/traefik.yml:/etc/traefik/traefik.yml'
      - './traefik/acme.json:/letsencrypt/acme.json'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: always
    labels:
      # Traefik 대시보드 라우터 설정
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.joshuatech.dev`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
      - "traefik.http.routers.dashboard.middlewares=cors-headers@file"

  fastapi:
    image: ghcr.io/joshua92y/joshtech-fastapi:latest
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.api.loadbalancer.server.port=8000'

      # HTTP → HTTPS 강제 리디렉션
      - 'traefik.http.routers.api.rule=Host(`api.joshuatech.dev`)'
      - 'traefik.http.routers.api.entrypoints=web'

      # HTTPS 라우터 설정
      - 'traefik.http.routers.api-secure.rule=Host(`api.joshuatech.dev`)'
      - 'traefik.http.routers.api-secure.entrypoints=websecure'
      - 'traefik.http.routers.api-secure.tls=true'
      - 'traefik.http.routers.api-secure.tls.certresolver=myresolver'
      - 'traefik.http.routers.api-secure.middlewares=cors-headers@file'
    env_file:
      - .env
    environment:
      - REDIS_HOST=10.0.10.193
      - REDIS_PORT=6379
      - DRAGONFLY_URL=redis://10.0.10.193:6379
      - R2_ENDPOINT=${R2_ENDPOINT}
      - R2_BUCKET=${R2_BUCKET}
      - R2_ACCESS_KEY=${R2_ACCESS_KEY}
      - R2_SECRET_KEY=${R2_SECRET_KEY}
      - DJANGO_API_URL=${DJANGO_API_URL}
    restart: always
