# apps/worker/dragonfly-worker-compose.yml
services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: dragonfly
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env

  r2_worker:
    image: ghcr.io/joshua92y/worker:latest
    container_name: worker
    platform: linux/arm64
    restart: always
    depends_on:
      - dragonfly
    env_file:
      - .env
    environment:
      R2_ENDPOINT: ${R2_ENDPOINT}
      R2_BUCKET: ${R2_BUCKET}
      R2_ACCESS_KEY: ${R2_ACCESS_KEY}
      R2_SECRET_KEY: ${R2_SECRET_KEY}
      DJANGO_API_URL: ${DJANGO_API_URL}
      DRAGONFLY_URL: redis://dragonfly:6379