# Generated by Django 5.2 on 2025-05-17 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="can_manage_users",
        ),
        migrations.RemoveField(
            model_name="role",
            name="can_upload",
        ),
        migrations.RemoveField(
            model_name="role",
            name="can_view_logs",
        ),
    ]
