# infra/oci/traefik/traefik.yml

log:
  level: DEBUG # 로그 수준: DEBUG / INFO / ERROR
  filePath: /var/log/traefik.log # Traefik 시스템 로그

accessLog:
  filePath: /var/log/access.log # 클라이언트 접근 로그
  bufferingSize: 100 # 버퍼 사이즈 (로그 성능 최적화)

api:
  dashboard: true # 웹 대시보드 활성화
  insecure: true # 개발용 대시보드 무인증 공개 (운영 시 false + 인증 설정)

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure # 모든 HTTP 요청을 HTTPS로 리디렉션
          scheme: https
  websecure:
    address: ':443'

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false # 기본적으로 모든 컨테이너 비노출 (라벨 필요)
    network: bridge

certificatesResolvers:
  myresolver:
    acme:
      email: admin@joshuatech.dev # 인증서 발급시 등록 이메일
      storage: /letsencrypt/acme.json # 인증서 저장 위치
      tlsChallenge: true # 포트 443 기반 인증
      caServer: https://acme-v02.api.letsencrypt.org/directory # Let's Encrypt production 서버

http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
