# Generated by Django 5.2 on 2025-05-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_contactmessage_failure_reason_contactmessage_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="from_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="message_stream",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="to_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
