# Generated by Django 5.2 on 2025-05-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="markdownpost",
            name="image",
            field=models.URLField(blank=True, help_text="대표 이미지", null=True),
        ),
        migrations.AddField(
            model_name="markdownpost",
            name="images",
            field=models.JSONField(
                blank=True, default=list, help_text="이미지 경로 배열", null=True
            ),
        ),
        migrations.AddField(
            model_name="markdownpost",
            name="link",
            field=models.URLField(blank=True, help_text="관련 링크", null=True),
        ),
        migrations.AddField(
            model_name="markdownpost",
            name="summary",
            field=models.TextField(blank=True, help_text="간단한 요약"),
        ),
        migrations.AddField(
            model_name="markdownpost",
            name="tag",
            field=models.CharField(blank=True, help_text="단일 태그", max_length=50),
        ),
        migrations.AddField(
            model_name="markdownpost",
            name="team",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='\n        예: [{"name": "홍길동", "role": "디자이너", "avatar": "/img.png", "linkedIn": "..."}]\n    ',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="markdownpost",
            name="content",
            field=models.TextField(help_text="마크다운 본문"),
        ),
    ]
