# Generated by Django 5.2.1 on 2025-06-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_markdownpost_image_markdownpost_images_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="markdownpost",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("work", "Work"),
                    ("project", "Project"),
                    ("post", "Post"),
                    ("page", "Page"),
                ],
                default=20240501,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
