# Generated by Django 5.2 on 2025-05-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("R2_Storage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filemeta",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="filemeta",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
