# Generated by Django 5.2 on 2025-05-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("R2_Storage", "0002_filemeta_deleted_at_filemeta_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="filemeta",
            name="deleted_by",
            field=models.CharField(
                default="admin", help_text="삭제 요청 유저", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="filemeta",
            name="deleted_from",
            field=models.CharField(
                blank=True,
                help_text="삭제 요청 위치 (예: web, fastapi, android)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="filemeta",
            name="is_purged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="filemeta",
            name="purged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="filemeta",
            name="uploaded_from",
            field=models.CharField(
                blank=True,
                help_text="업로드 요청 위치 (예: web, android, api)",
                max_length=255,
                null=True,
            ),
        ),
    ]
