# Generated by Django 5.2 on 2025-05-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("R2_Storage", "0003_filemeta_deleted_by_filemeta_deleted_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filemeta",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="filemeta",
            name="restored_by",
            field=models.CharField(
                blank=True, help_text="복구 요청 유저", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="filemeta",
            name="restored_from",
            field=models.CharField(
                blank=True,
                help_text="복구 요청 위치 (예: web, fastapi, android)",
                max_length=255,
                null=True,
            ),
        ),
    ]
