# generated by datamodel-codegen:
#   filename:  BlacklistedToken.json
#   timestamp: 2025-05-21T02:47:02+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class BlacklistedToken(BaseModel):
    id: Optional[int] = Field(None, title='id')
    token: int = Field(..., title='token')
    blacklisted_at: Optional[datetime] = Field(None, title='blacklisted at')
