# generated by datamodel-codegen:
#   filename:  ContactMessage.json
#   timestamp: 2025-05-01T16:21:22+00:00

from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, Field


class ContactMessage(BaseModel):
    id: Optional[str] = None
    name: str = Field(..., description="보낸 사람 이름", example="홍길동")
    email: str = Field(..., description="보낸 사람 이메일", example="hong@example.com")
    message: str = Field(
        ..., description="문의 내용", example="포트폴리오 잘 봤습니다. 연락드릴게요!"
    )
    created_at: datetime = Field(
        ..., description="문의 접수 시간", example="2025-05-01T12:00:00"
    )
