# generated by datamodel-codegen:
#   filename:  ContactMessage.json
#   timestamp: 2025-05-06T06:54:57+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class ContactMessage(BaseModel):
    id: Optional[int] = Field(None, title='ID')
    name: str = Field(..., title='name')
    email: str = Field(..., title='email')
    message: str = Field(..., title='message')
    created_at: Optional[datetime] = Field(None, title='created at')
