# generated by datamodel-codegen:
#   filename:  ContactMessage.json
#   timestamp: 2025-05-21T02:46:40+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class ContactMessage(BaseModel):
    id: Optional[int] = Field(None, title='ID')
    name: str = Field(..., title='name')
    email: str = Field(..., title='email')
    subject: str = Field(..., title='subject')
    message: str = Field(..., title='message')
    sent: Optional[bool] = Field(False, title='sent')
    sent_at: Optional[datetime] = Field(None, title='sent at')
    created_at: Optional[datetime] = Field(None, title='created at')
    failure_reason: Optional[str] = Field(None, title='failure reason')
    from_email: Optional[str] = Field(None, title='from email')
    to_email: Optional[str] = Field(None, title='to email')
    message_stream: Optional[str] = Field(None, title='message stream')
