# generated by datamodel-codegen:
#   filename:  ContentType.json
#   timestamp: 2025-05-21T02:46:21+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class ContentType(BaseModel):
    id: Optional[int] = Field(None, title='ID')
    app_label: str = Field(..., title='app label')
    model: str = Field(..., title='python 모델 클래스 명')
