# generated by datamodel-codegen:
#   filename:  FileMeta.json
#   timestamp: 2025-05-17T06:03:55+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class FileMeta(BaseModel):
    id: Optional[int] = Field(None, title='ID')
    user: int = Field(..., title='user')
    uploaded_from: Optional[str] = Field(None, title='uploaded from')
    key: str = Field(..., title='key')
    filename: str = Field(..., title='filename')
    content_type: str = Field(..., title='content type')
    size: int = Field(..., title='size')
    uploaded_at: datetime = Field(..., title='uploaded at')
    is_deleted: Optional[bool] = Field(False, title='is deleted')
    deleted_at: Optional[datetime] = Field(None, title='deleted at')
    deleted_by: Optional[str] = Field('admin', title='deleted by')
    deleted_from: Optional[str] = Field(None, title='deleted from')
    is_purged: Optional[bool] = Field(False, title='is purged')
    purged_at: Optional[datetime] = Field(None, title='purged at')
