# generated by datamodel-codegen:
#   filename:  Group.json
#   timestamp: 2025-05-21T02:46:16+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Group(BaseModel):
    id: Optional[int] = Field(None, title='ID')
    name: str = Field(..., title='이름')
