# generated by datamodel-codegen:
#   filename:  LogEntry.json
#   timestamp: 2025-05-21T02:46:08+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class 액션플래그(Enum):
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3


class LogEntry(BaseModel):
    id: Optional[int] = Field(None, title='ID')
    action_time: Optional[datetime] = Field(
        '2025-05-21 02:46:04.623227+00:00', title='액션 타임'
    )
    user: int = Field(..., title='사용자')
    content_type: Optional[int] = Field(None, title='콘텐츠 타입')
    object_id: Optional[str] = Field(None, title='오브젝트 아이디')
    object_repr: str = Field(..., title='오브젝트 표현')
    action_flag: 액션플래그 = Field(..., title='액션 플래그')
    change_message: Optional[str] = Field(None, title='메시지 변경')
