# generated by datamodel-codegen:
#   filename:  MarkdownPost.json
#   timestamp: 2025-05-27T08:10:23+00:00

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class MarkdownPost(BaseModel):
    id: Optional[int] = Field(None, title='ID')
    title: str = Field(..., title='title')
    slug: Optional[str] = Field(None, title='slug')
    summary: Optional[str] = Field(None, title='summary')
    content: str = Field(..., title='content')
    image: Optional[str] = Field(None, title='image')
    images: Optional[Dict[str, Any]] = Field([], title='images')
    tag: Optional[str] = Field(None, title='tag')
    link: Optional[str] = Field(None, title='link')
    team: Optional[Dict[str, Any]] = Field([], title='team')
    author: int = Field(..., title='author')
    is_published: Optional[bool] = Field(False, title='is published')
    published_at: Optional[datetime] = Field(None, title='published at')
    created_at: Optional[datetime] = Field(None, title='created at')
    updated_at: Optional[datetime] = Field(None, title='updated at')
