# generated by datamodel-codegen:
#   filename:  Permission.json
#   timestamp: 2025-05-21T02:46:12+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Permission(BaseModel):
    id: Optional[int] = Field(None, title='ID')
    name: str = Field(..., title='이름')
    content_type: int = Field(..., title='콘텐츠 타입')
    codename: str = Field(..., title='코드명')
