# generated by datamodel-codegen:
#   filename:  Project.json
#   timestamp: 2025-05-08T03:37:43+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class Project(BaseModel):
    id: Optional[int] = Field(None, title='ID')
    title: str = Field(..., title='title')
    description: str = Field(..., title='description')
    link: Optional[str] = Field(None, title='link')
    tag: Optional[str] = Field(None, title='tag')
    created_at: Optional[datetime] = Field(None, title='created at')
