# generated by datamodel-codegen:
#   filename:  Project.json
#   timestamp: 2025-05-01T16:21:18+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Project(BaseModel):
    id: Optional[str] = None
    title: str = Field(..., description="프로젝트 제목", example="AI Tone Converter")
    description: str = Field(..., description="프로젝트 설명", example="말투를 AI로 분석하고 변환해주는 웹 앱")
    link: Optional[str] = Field(None, description="프로젝트 링크 (GitHub 등)", example="https://github.com/yourname/tone-c")
    tag: Optional[str] = None = Field(None,description="해시테그", example="#웹앱")
    created_at: Optional[str] = None
