# generated by datamodel-codegen:
#   filename:  Resume.json
#   timestamp: 2025-06-10T06:07:26+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class Resume(BaseModel):
    id: Optional[int] = Field(None, title='ID')
    name: str = Field(..., title='name')
    email: str = Field(..., title='email')
    phone: str = Field(..., title='phone')
    summary: str = Field(..., title='summary')
    created_at: Optional[datetime] = Field(None, title='created at')
