# generated by datamodel-codegen:
#   filename:  Resume.json
#   timestamp: 2025-05-01T16:21:14+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Resume(BaseModel):
    id: Optional[str] = None
    name: str = Field(..., description="이름", example="홍길동")
    email: str = Field(..., description="이메일 주소", example="hong@example.com")
    phone: str = Field(..., description="전화번호", example="010-1234-5678")
    summary: str = Field(
        ..., description="요약 소개", example="FastAPI + Django 기반 백엔드 개발자"
    )
    created_at: Optional[str] = None
