# generated by datamodel-codegen:
#   filename:  Role.json
#   timestamp: 2025-05-16T08:12:27+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Role(BaseModel):
    id: Optional[int] = Field(None, title='ID')
    name: str = Field(..., title='name')
    description: Optional[str] = Field(None, title='description')
    can_upload: Optional[bool] = Field(False, title='can upload')
    can_view_logs: Optional[bool] = Field(False, title='can view logs')
    can_manage_users: Optional[bool] = Field(False, title='can manage users')
