# generated by datamodel-codegen:
#   filename:  Role.json
#   timestamp: 2025-05-17T06:03:48+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Role(BaseModel):
    id: Optional[int] = Field(None, title='ID')
    name: str = Field(..., title='name')
    description: Optional[str] = Field(None, title='description')
