# generated by datamodel-codegen:
#   filename:  UserDeviceToken.json
#   timestamp: 2025-05-27T08:25:42+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class UserDeviceToken(BaseModel):
    id: Optional[int] = Field(None, title='ID')
    user: int = Field(..., title='user')
    uuid: Optional[str] = Field('a1a4a4c7-f982-4959-bc41-83c995b7d0fe', title='uuid')
    jti: str = Field(..., title='jti')
    device_name: Optional[str] = Field(None, title='device name')
    created_at: Optional[datetime] = Field(
        '2025-05-27 08:25:39.284039+00:00', title='created at'
    )
    last_used_at: Optional[datetime] = Field(
        '2025-05-27 08:25:39.284084+00:00', title='last used at'
    )
    is_active: Optional[bool] = Field(True, title='is active')
