# generated by datamodel-codegen:
#   filename:  UserDeviceToken.json
#   timestamp: 2025-05-21T02:46:45+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class UserDeviceToken(BaseModel):
    id: Optional[int] = Field(None, title='ID')
    user: int = Field(..., title='user')
    uuid: Optional[str] = Field('c171fc41-d00a-4877-adad-c01dc8788cb8', title='uuid')
    jti: str = Field(..., title='jti')
    device_name: Optional[str] = Field(None, title='device name')
    created_at: Optional[datetime] = Field(
        '2025-05-21 02:46:40.758473+00:00', title='created at'
    )
    last_used_at: Optional[datetime] = Field(
        '2025-05-21 02:46:40.758473+00:00', title='last used at'
    )
    is_active: Optional[bool] = Field(True, title='is active')
