# generated by datamodel-codegen:
#   filename:  User.json
#   timestamp: 2025-05-21T02:46:54+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class User(BaseModel):
    id: Optional[int] = Field(None, title='ID')
    password: str = Field(..., title='비밀번호')
    last_login: Optional[datetime] = Field(None, title='마지막 로그인')
    is_superuser: Optional[bool] = Field(False, title='최상위 사용자 권한')
    username: str = Field(..., title='사용자 이름')
    first_name: Optional[str] = Field(None, title='이름')
    last_name: Optional[str] = Field(None, title='성')
    email: Optional[str] = Field(None, title='이메일 주소')
    is_staff: Optional[bool] = Field(False, title='스태프 권한')
    is_active: Optional[bool] = Field(True, title='활성')
    date_joined: Optional[datetime] = Field(
        '2025-05-21 02:46:50.031123+00:00', title='등록일'
    )
    role: Optional[int] = Field(None, title='role')
