# generated by datamodel-codegen:
#   filename:  UserDeviceToken.json
#   timestamp: 2025-06-10T06:07:48+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class UserDeviceToken(BaseModel):
    id: Optional[int] = Field(None, title='ID')
    user: int = Field(..., title='user')
    uuid: Optional[str] = Field('5e859860-7bba-41fc-8ed3-77f05733b8e1', title='uuid')
    jti: str = Field(..., title='jti')
    device_name: Optional[str] = Field(None, title='device name')
    created_at: Optional[datetime] = Field(
        '2025-06-10 06:07:42.558047+00:00', title='created at'
    )
    last_used_at: Optional[datetime] = Field(
        '2025-06-10 06:07:42.558087+00:00', title='last used at'
    )
    is_active: Optional[bool] = Field(True, title='is active')
