# Generated by Django 5.2 on 2025-05-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tag",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
