# generated by datamodel-codegen:
#   filename:  ContentType.json
#   timestamp: 2025-05-01T09:15:02+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class ContentType(BaseModel):
    id: Optional[str] = None
    app_label: str
    model: str
