# generated by datamodel-codegen:
#   filename:  ContactMessage.json
#   timestamp: 2025-05-01T08:45:54+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class ContactMessage(BaseModel):
    id: Optional[str] = None
    name: str
    email: str
    message: str
    created_at: Optional[str] = None
