# generated by datamodel-codegen:
#   filename:  Group.json
#   timestamp: 2025-05-01T09:14:54+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Group(BaseModel):
    id: Optional[str] = None
    name: str
