# generated by datamodel-codegen:
#   filename:  LogEntry.json
#   timestamp: 2025-05-01T09:14:47+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class LogEntry(BaseModel):
    id: Optional[str] = None
    action_time: str
    user: str
    content_type: Optional[str] = None
    object_id: Optional[str] = None
    object_repr: str
    action_flag: str
    change_message: Optional[str] = None
