# generated by datamodel-codegen:
#   filename:  Permission.json
#   timestamp: 2025-05-01T09:14:51+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Permission(BaseModel):
    id: Optional[str] = None
    name: str
    content_type: str
    codename: str
