# generated by datamodel-codegen:
#   filename:  Project.json
#   timestamp: 2025-05-01T08:44:54+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Project(BaseModel):
    id: Optional[str] = None
    title: str
    description: str
    link: Optional[str] = None
    created_at: Optional[str] = None
