# generated by datamodel-codegen:
#   filename:  Resume.json
#   timestamp: 2025-05-01T09:26:49+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Resume(BaseModel):
    id: Optional[str] = None
    name: str
    email: str
    phone: str
    summary: str
    created_at: Optional[str] = None
