# generated by datamodel-codegen:
#   filename:  Session.json
#   timestamp: 2025-05-01T09:15:05+00:00

from __future__ import annotations

from pydantic import BaseModel


class Session(BaseModel):
    session_key: str
    session_data: str
    expire_date: str
