# generated by datamodel-codegen:
#   filename:  User.json
#   timestamp: 2025-05-01T09:14:58+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class User(BaseModel):
    id: Optional[str] = None
    password: str
    last_login: Optional[str] = None
    is_superuser: bool
    username: str
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    email: Optional[str] = None
    is_staff: bool
    is_active: bool
    date_joined: str
